---
- name: install dependencies
  action: yum pkg=redis state=installed

- name: download logstash release
  action: get_url url={{logstash_url}} dest=/tmp/{{logstash_file}}

- name: create toplevel logstash directory
  action: file path=/opt/logstash owner=root group=root mode=0755

- name: create logstash subdirectories
  action: file path=/opt/logstash/{{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - bin
    - etc
    - share

- name: deploy logstash.conf
  action: copy src=../files/logstash/logstash.conf dest=/opt/logstash/etc/logstash.conf owner=root group=root mode=0644

- name: create /var/log/logstash directory
  action: file path=/var/log/logstash owner=root group=root mode=0755 state=directory

- name: move {{logstash_file}} to /opt/logstash/share
  action: command mv -f /tmp/{{logstash_file}} /opt/logstash/share 
          creates=/opt/logstash/share/{{logstash_file}}

- name: symlink logstash.jar to {{logstash_file}}
  action: file src=/opt/logstash/share/{{logstash_file}} dest=/opt/logstash/share/logstash.jar state=link
