---
- name: example audit playbook
  hosts: all
  user: root
  gather_facts: no

  vars:
      ignore_pkgs: jre

  tasks:

      - name: verify auditd configuration
        action: auditd

      - name: verify installed packages are gpg signed
        signed_pkgs: exclude={{ignore_pkgs}}

      - name: verify iptables/firewall is configured
        action: iptables

      - name: verify selinux configuration
        action: selinux_status

      - name: examine filesystem
        filesystem: exclude=/var/lib/ansible
