---
- name: apply common role to all
  user: root
  hosts: all
  roles:
      - common

- name: apply workstation role
  user: root
  hosts: workstation
  roles:
      - workstation

- name: apply home role
  user: root
  hosts: home
  roles:
      - home

- name: apply java role
  user: root
  hosts: java_hosts
  roles:
      - java
