---
- name: apply common role to all
  user: root
  hosts: all

  roles:
      - common

- name: apply workstation role
  user: root
  hosts: workstation

  roles:
      - workstation
      - java

- name: apply home role
  user: root
  hosts: home

  roles:
      - home
