---
# some inspiration comes from:
# http://tabs.mediahackers.org/
planet_repo: git://github.com/rubys/venus.git
planet_dest: /home/stephenf/Source/venus
planet_venv: /home/stephenf/Public/venus_venv
staging_dir: /tmp/planets
planet_pub_dir: /home/stephenf/public_html/planets
planets:
    - news-world
    - news-tech
    - listen
    - potpourri
    - listen

planet:
    name: Spigot
    log_level: INFO
    feed_timeout: 20
planetoids:
    news-world:
        name: World News
        description: A set of feeds that cover world and local news.
        log_level: DEBUG
        feed_timeout: 20
        feeds:
            - name: Democracy in America
              url: http://www.economist.com/blogs/democracyinamerica/atom.xml
            - name: UO Matters
              url: http://uomatters.blogspot.com/feeds/posts/default
            - name: Lexingtons Notebook
              url: http://www.economist.com/blogs/lexington/atom.xml
            - name: NPR World News
              url: http://www.npr.org/rss/rss.php?id=1004
            - name: NPR US News
              url: http://www.npr.org/rss/rss.php?id=1003
            - name: NPR The Two Way
              url: http://www.npr.org/rss/rss.php?id=1001
            - name: BBC News
              url: http://feeds.bbci.co.uk/news/rss.xml
            - name: New York Times
              url: http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
    news-tech:
        name: Tech News
        description: A set of blogs that cover news in the Tech world.
        log_level: DEBUG
        feed_timeout: 20
        feeds:
            - name: DroidLife
              url: http://feeds.feedburner.com/DroidLife
            - name: Ars Technica
              url: http://arstechnica.com/index.ars/rss
            - name: Raspberry Pi
              url: http://www.raspberrypi.org/feed
            - name: Gmail
              url: http://gmailblog.blogspot.com/atom.xml
            - name: Google
              url: http://googleblog.blogspot.com/atom.xml
            - name: Google OSS
              url: http://google-opensource.blogspot.com/feeds/posts/default
            - name: Google Voice
              url: http://googlevoiceblog.blogspot.com/atom.xml
            - name: Google Mobile
              url: http://googlemobile.blogspot.com/atom.xml
            - name: The Register
              url: http://www.theregister.co.uk/headlines.atom
    listen:
        name: Listen
        description: A collection of podcasts I find interesting.
        log_level: DEBUG
        feed_timeout: 20
        feeds:
            - name: 99% Invisible
              url: http://feeds.99percentinvisible.org/99percentinvisible
              filters: podcast.xslt
            - name: Language Bites
              url: http://www.rte.ie/radio1/podcast/podcast_languagebites.xml
            - name: The Memory Palace
              url: http://feeds.feedburner.com/thememorypalace
            - name: This American Life
              url: http://feeds.thisamericanlife.org/talpodcast
              filters: podcast.xslt
            - name: RadioLab
              url: http://feeds.wnyc.org/radiolab?format=xml
            - name: NPR Pop Culture
              url: http://www.npr.org/templates/rss/podlayer.php?id=1048
            - name: Ask Me Another
              url: http://www.npr.org/rss/podcast.php?id=510299
            - name: NPR Fresh Air
              url: http://www.npr.org/rss/podcast.php?id=13
            - name: Planet Money
              url: http://www.npr.org/rss/podcast.php?id=510289
            - name: Wait Wait ... 
              url: http://www.npr.org/rss/podcast.php?id=35
            - name: PBS NewsHour
              url: http://feeds.pbs.org/pbs/newshour/headlines-audio
            - name: Sweetness and Light
              url: http://www.npr.org/templates/rss/podlayer.php?id=4499275
    potpourri:
        name: Potpourri
        description: Comics and other blogs I find interesting and amusing.
        log_level: DEBUG
        feed_timeout: 20
        feeds:
            - name: XKCD
              url: http://xkcd.com/rss.xml
              filters: alttext.xslt
            - name: what if?
              url: http://what-if.xkcd.com/feed.atom
            - name: Text From Dog
              url: http://textfromdog.tumblr.com/rss
            - name: sticky comics
              url: http://www.stickycomics.com/feed/
            - name: DevOps Reactions
              url: http://devopsreactions.tumblr.com/rss
            - name: Magical Game Time
              url: http://magicalgametime.com/rss
            - name: Hyperbole and a Half
              url: http://hyperboleandahalf.blogspot.com/feeds/posts/default
    devzoo:
        name: Linux, DevOps, and more
        description: |-
            A collection of blogs and planets that cover Linux, NMS,
            Systems Administration, DevOps, Networking, and SDN.
        log_level: DEBUG
        feed_timeout: 20
        feeds:
            - name: Planet GNOME
              url: https://planet.gnome.org/atom.xml
            - name: Planet Fedora
              url: http://planet.fedoraproject.org/atom.xml
            - name: Planet CentOS
              url: http://planet.centos.org/atom.xml
            - name: Planet Freedesktop
              url: http://planet.freedesktop.org/rss20.xml
            - name: Kernel Planet
              url: http://kernelplanet.org/rss20.xml
            - name: KernelTrap
              url: http://kerneltrap.org/node/feed
            - name: Planet Sysadmin
              url: http://planetsysadmin.com/atom.xml
            - name: Planet Puppet
              url: http://www.planetpuppet.org/?type=atom10
            - name: Adventures in OSS
              url: http://www.adventuresinoss.com/?feed=rss2
            - name: Packet Pushers
              url: http://feeds.feedburner.com/PacketPushersBlogsOnly
            - name: Network Static
              url: http://feeds.feedburner.com/Networkstatic
