---
emacs_lisp_dir: .emacs.d/lisp
emacs_pkg_dir: .emacs.d/package
emacs_d_dirs:
    - .emacs.d
    - "{{emacs_lisp_dir}}"
    - "{{emacs_pkg_dir}}"
emacs_addon_files:
    - name: gnus-alias.el
      url: http://www.emacswiki.org/emacs/download/gnus-alias.el
emacs_addon_git:
    - name: use-package
      url: https://github.com/jwiegley/use-package.git
    - name: org-mode
      url: git://orgmode.org/org-mode.git
    - name: yaml-mode
      url: https://github.com/yoshiki/yaml-mode.git
    - name: twittering-mode
      url: https://github.com/hayamiz/twittering-mode.git
#    - name: offlineimap-el
#      url: git://git.naquadah.org/offlineimap-el.git
