---
- name: Install EPEL EL6 repository
  command: rpm -Uvh  http://{{epel_server}}/6/{{ansible_architecture}}/{{epel_6_release}} creates=/etc/yum.repos.d/epel.repo
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
