---
- name: Install elrepo.org EL6 repository
  command: rpm -Uvh  http://{{elrepo_server}}/{{elrepo_6_release}} creates=/etc/yum.repos.d/elrepo.repo
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
