---
- hosts: logcentral
  user: root

  vars_files:
    - ../vars/global_vars.yml
    - ../vars/main.yml

  tasks:
    - include: ../tasks/setup.yml

  handlers:
    - include: ../handlers/logstash.yml
