---
- hosts: all

  vars_files:
    - ../vars/global_vars.yml

  tasks:
    - name: Install minicom
      action: yum name=minicom state=installed

    - name: Copy site default minirc.dfl
      action: copy src=files/minirc.dfl dest=/etc/minirc.dfl
              owner=root group=root mode=0644 backup=yes

    - name: Make minicom usable by those in group $minicom_user_group
      action: file path=/usr/bin/minicom group=$minicom_user_group mode=2755
