---
- name: Install redis dependency, requires EPEL for Centos and RHEL
  action: yum pkg=redis state=installed

- name: Download logstash release
  action: get_url url=${logstash_url} dest=/tmp/${logstash_file}

- name: Create toplevel logstash directory
  action: file path=/opt/logstash owner=root group=root mode=0755

- name: Create logstash subdirectory $item
  action: file path=/opt/logstash/$item owner=root group=root mode=0755 state=directory
  with_items:
    - bin
    - etc
    - share

- name: Copy logstash.conf into place
  action: copy src=files/logstash.conf dest=/opt/logstash/etc/logstash.conf owner=root group=root mode=0644

- name: Create /var/log/logstash directory
  action: file path=/var/log/logstash owner=root group=root mode=0755 state=directory

- name: Move ${logstash_file} to /opt/logstash/share
  action: command mv -f /tmp/${logstash_file} /opt/logstash/share creates=/opt/logstash/share/${logstash_file}

- name: Symlink logstash.jar to ${logstash_file}
  action: file src=/opt/logstash/share/${logstash_file} dest=/opt/logstash/share/logstash.jar state=link
